name: Publish
on:
  push:
    tags: ["*"]
jobs:
  nuget-push:
    runs-on: ubuntu-latest
    environment: NuGet
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: dotnet pack
      - run: dotnet nuget push 'ScipDotnet/bin/Debug/*.nupkg' --source 'nuget.org' --api-key '${{ secrets.NUGET_APIKEY }}' --skip-duplicate
          
          